import type { Metadata } from 'next'
import {Noto_Serif} from 'next/font/google'
import './globals.css'
import { Graphik } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Graphik.className}>{children}</body>
    </html>
  )
}
